In [1]:
import pandas as pd

df = pd.read_csv('/content/Student_Performance_DT - Student_Performance_DT (1).csv')

df.head()

,Study_Hours,Attendance,Previous_Score,Assignments_Completed,Sleep_Hours,Participation,Internet_Access,Extracurricular,Final_Result
0,5.5,89.1,89.0,9,7.2,8,Yes,Yes,Pass
1,4.2,100.0,81.9,6,7.4,4,Yes,No,Pass
2,5.8,61.2,68.9,6,7.6,1,No,No,Fail
3,7.5,84.8,58.3,5,8.1,7,No,No,Pass
4,4.0,70.2,78.5,3,7.3,1,Yes,Yes,Pass

In [2]:
df.shape

(500, 9)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Study_Hours            500 non-null    float64
 1   Attendance             500 non-null    float64
 2   Previous_Score         500 non-null    float64
 3   Assignments_Completed  500 non-null    int64
 4   Sleep_Hours            500 non-null    float64
 5   Participation          500 non-null    int64
 6   Internet_Access        500 non-null    object
 7   Extracurricular        500 non-null    object
 8   Final_Result           500 non-null    object
dtypes: float64(4), int64(2), object(3)
memory usage: 35.3+ KB

In [4]:
df.isnull().sum()

Study_Hours              0
Attendance               0
Previous_Score           0
Assignments_Completed    0
Sleep_Hours              0
Participation            0
Internet_Access          0
Extracurricular          0
Final_Result             0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df = df.drop_duplicates()

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
le = LabelEncoder()

df['Internet_Access'] = le.fit_transform(df['Internet_Access'])
df['Extracurricular'] = le.fit_transform(df['Extracurricular'])
df['Final_Result'] = le.fit_transform(df['Final_Result'])

df.head()

,Study_Hours,Attendance,Previous_Score,Assignments_Completed,Sleep_Hours,Participation,Internet_Access,Extracurricular,Final_Result
0,5.5,89.1,89.0,9,7.2,8,1,1,1
1,4.2,100.0,81.9,6,7.4,4,1,0,1
2,5.8,61.2,68.9,6,7.6,1,0,0,0
3,7.5,84.8,58.3,5,8.1,7,0,0,1
4,4.0,70.2,78.5,3,7.3,1,1,1,1

In [12]:
X = df.drop('Final_Result', axis=1)
y = df['Final_Result']

In [13]:
X.head()

,Study_Hours,Attendance,Previous_Score,Assignments_Completed,Sleep_Hours,Participation,Internet_Access,Extracurricular
0,5.5,89.1,89.0,9,7.2,8,1,1
1,4.2,100.0,81.9,6,7.4,4,1,0
2,5.8,61.2,68.9,6,7.6,1,0,0
3,7.5,84.8,58.3,5,8.1,7,0,0
4,4.0,70.2,78.5,3,7.3,1,1,1

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [18]:
X_train.shape, X_test.shape

((400, 8), (100, 8))

In [19]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [20]:
y_pred = dt.predict(X_test)

In [27]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Default Decision Tree")
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

Default Decision Tree
Accuracy: 0.67
Precision: 0.7166666666666667
Recall: 0.7288135593220338
F1-score: 0.7226890756302521

In [22]:
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [3, 5, 7, 10, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

In [23]:
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [3, 5, 7, 10, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

In [25]:
from sklearn.model_selection import GridSearchCV

In [26]:
grid_search = GridSearchCV(
    DecisionTreeClassifier(random_state=42),
    param_grid,
    cv=5,
    scoring='accuracy'
)

grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=42),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [3, 5, 7, 10, None],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10]},
             scoring='accuracy')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [28]:
print("Best Parameters:")
print(grid_search.best_params_)

best_dt = grid_search.best_estimator_

best_dt.fit(X_train, y_train)

y_pred_tuned = best_dt.predict(X_test)

accuracy_tuned = accuracy_score(y_test, y_pred_tuned)
precision_tuned = precision_score(y_test, y_pred_tuned)
recall_tuned = recall_score(y_test, y_pred_tuned)
f1_tuned = f1_score(y_test, y_pred_tuned)

print("\nTuned Decision Tree")
print("Accuracy:", accuracy_tuned)
print("Precision:", precision_tuned)
print("Recall:", recall_tuned)
print("F1-score:", f1_tuned)

results = pd.DataFrame({
    "Metric": ["Accuracy", "Precision", "Recall", "F1-score"],
    "Default Model": [accuracy, precision, recall, f1],
    "Tuned Model": [accuracy_tuned, precision_tuned, recall_tuned, f1_tuned]
})

print("\nDefault vs Tuned Model")
display(results)

if accuracy_tuned > accuracy:
    print("Hyperparameter tuning improved the model performance.")
elif accuracy_tuned < accuracy:
    print("Hyperparameter tuning decreased the model performance.")
else:
    print("Hyperparameter tuning did not change the model performance.")

Best Parameters:
{'criterion': 'gini', 'max_depth': 10, 'min_samples_leaf': 4, 'min_samples_split': 2}

Tuned Decision Tree
Accuracy: 0.7
Precision: 0.7543859649122807
Recall: 0.7288135593220338
F1-score: 0.7413793103448276

Default vs Tuned Model

      Metric  Default Model  Tuned Model
0   Accuracy       0.670000     0.700000
1  Precision       0.716667     0.754386
2     Recall       0.728814     0.728814
3   F1-score       0.722689     0.741379

Hyperparameter tuning improved the model performance.

In [29]:
from google.colab import files

files.download('/content/Student_Performance_DT - Student_Performance_DT (1).csv')